name: shakshak
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.9.3
  shared_preferences: ^2.3.2
  flutter_bloc: ^8.1.6
  cached_network_image: ^3.4.1
  smooth_page_indicator: ^1.2.0+3
  flutter_svg: ^2.0.10+1
  awesome_snackbar_content: ^0.1.4
  skeletonizer: ^2.1.0+1
  flutter_launcher_icons: ^0.13.1
  go_router: ^14.6.0
  modal_progress_hud_nsn: ^0.5.1
  animate_do: ^3.3.4
  flutter_spinkit: ^5.2.1
  get_it: ^7.7.0
  intl_phone_field: ^3.2.0
  pinput: ^5.0.0
  expandable: ^5.0.1
  image_picker: ^1.1.2
  url_launcher: ^6.3.1
  dio: ^5.7.0
  dartz: ^0.10.1
  bottom_picker: ^3.2.1
  dropdown_button2: ^2.3.9
  pretty_dio_logger: ^1.3.1
  google_maps_flutter: ^2.6.1
  flutter_rating_bar: ^4.0.1
  geocode: ^1.0.3
  location: ^7.0.1
  intl: ^0.20.2
  webview_flutter_plus: ^0.4.19


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/svg/
    - assets/fonts/

  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Light.ttf
          weight: 300
        - asset: assets/fonts/Cairo-Regular.ttf
          weight: 400
        - asset: assets/fonts/Cairo-Medium.ttf
          weight: 500
        - asset: assets/fonts/Cairo-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 700
flutter_intl:
  enabled: true
